version: '3'
services:
  server:
    image: joellord/conftracker
    ports:
      - "3000:3000"
  database:
    image: joellord/conftracker-db
    ports:
      - "3306:3306"
    volumes:
#       - ./dbdata:/var/lib/mysql/data
      - ./dbdata:/var/lib/mysql
